- name: playbook to create a cron job to the nodes

  hosts: all

  tasks:

    - name: create a cron job
      cron:
        name: datejob
        hour: "12"
        user: root
        job: "date >> /root/datefile"
